# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jovial Design by Aaron Blythe
email: aaron dot blythe at gmail dot com
description: > # this means to ignore newlines until "baseurl:"
  Random thoughts on tech, devops, meetups, conferences, and other stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ablythe
github_username: aaronblythe
gitlab_username: aaronblythe


# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  #- jekyll-assets
  - bootstrap-sass
  - uglifier
exclude:
  - Gemfile
  - Gemfile.lock
#assets:
#  assets:
#    - "*.png"
#    - "*.jpg"
#  sources:
#    - assets/images
#    - assets/images/icons
#    - assets/javascripts
#    - assets/css
#  compress:
#    css:  sass
#    js:   uglifier